#!/bin/bash
# A script that uses 'xdg-mime' to fetch the default apps on the system.
# Dependencies: 'xdg-mime', 'xdg-settings'
# Written by simonizor 5/27/2017 - http://www.simonizor.gq/scripts

bold=$(tput bold; tput setaf 7)
norm=$(tput sgr0)

programisinstalled () {
  return=1
  type "$1" >/dev/null 2>&1 || { return=0; }
}

xdgfetchmain () {
    case $1 in
        -h*|--h*)
            echo "${bold}xdgfetch usage${norm}:"
            echo
            echo "${bold}xdgfetch${norm}   : Shows default xdg-mime applications"
            echo "${bold}xdgfetch -h${norm}: Shows this help output"
            echo "${bold}xdgfetch -c${norm}: Changes the color of bold text. Options 1-6."
            echo "  Ex: 'xdgfetch -c 1', 'xdgfetch -c 1 -b'"
            echo "${bold}xdgfetch -b${norm}: Shows default xdg browser"
            echo "${bold}xdgfetch -m${norm}: Shows default xdg email app"
            echo "${bold}xdgfetch -a${norm}: Shows default xdg audio app"
            echo "${bold}xdgfetch -v${norm}: Shows default xdg video app"
            echo "${bold}xdgfetch -i${norm}: Shows default xdg image viewer"
            echo "${bold}xdgfetch -t${norm}: Shows default xdg text editor"
            echo
            ;;
        -c*|--c*)
            case $2 in
                1)
                    bold=$(tput bold; tput setaf 1)
                    xdgfetchmain "$3"
                    ;;
                2)
                    bold=$(tput bold; tput setaf 2)
                    xdgfetchmain "$3"
                    ;;
                3)
                    bold=$(tput bold; tput setaf 3)
                    xdgfetchmain "$3"
                    ;;
                4)
                    bold=$(tput bold; tput setaf 4)
                    xdgfetchmain "$3"
                    ;;
                5)
                    bold=$(tput bold; tput setaf 5)
                    xdgfetchmain "$3"
                    ;;
                6)
                    bold=$(tput bold; tput setaf 6)
                    xdgfetchmain "$3"
                    ;;
                *)
                    bold=$(tput bold; tput setaf 7)
                    xdgfetchmain "$3"
                    ;;
            esac
            ;;
        -b*|--b*)
            XDGBROWSER="$(xdg-settings get default-web-browser)" || XDGBROWSER="Not set!        "
            case $XDGBROWSER in
                *Pale*|*pale*)
                    echo "${bold}Browser: ${norm}Pale Moon"
                    ;;
                *firefox*)
                    echo "${bold}Browser: ${norm}Firefox"
                    ;;
                *google*)
                    echo "${bold}Browser: ${norm}Google Chrome"
                    ;;
                *chromium*)
                    echo "${bold}Browser: ${norm}Chromium"
                    ;;
                *)
                    echo "${bold}Browser: ${norm}${XDGBROWSER::-8}"
                    ;;
            esac
            ;;
        -m*|--m*)
            XDGMAILTO="$(xdg-mime query default x-scheme-handler/mailto)" || XDGMAILTO="Not set!        "
            case $XDGMAILTO in
                *thunderbird*|*Thunderbird*)
                    echo "${bold}Email:   ${norm}Thunderbird"
                    ;;
                *kmail*)
                    echo "${bold}Email:   ${norm}KMail"
                    ;;
                *)
                    echo "${bold}Email:   ${norm}${XDGMAILTO::-8}"
                    ;;
            esac
            ;;
        -a*|--a*)
            XDGAUDIO="$(xdg-mime query default audio/flac)" || XDGAUDIO="Not set!        "
            case $XDGAUDIO in
                *audacious*|*Audacious*)
                    echo "${bold}Audio:   ${norm}Audacious"
                    ;;
                *mpv*)
                    echo "${bold}Audio:   ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    echo "${bold}Audio:   ${norm}VLC"
                    ;;
                *amarok*|*Amarok*)
                    echo "${bold}Audio:   ${norm}Amarok"
                    ;;
                *deadbeef*)
                    echo "${bold}Audio:   ${norm}DeaDBeeF"
                    ;;
                *)
                    echo "${bold}Audio:   ${norm}${XDGAUDIO::-8}"
                    ;;
            esac
            ;;
        -v*|--v*)
            XDGVIDEO="$(xdg-mime query default video/mp4)" || XDGVIDEO="Not set!        "
            case $XDGVIDEO in
                *mpv*)
                    echo "${bold}Video:   ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    echo "${bold}Video:   ${norm}VLC"
                    ;;
                *mplayer*)
                    echo "${bold}Video:   ${norm}Mplayer"
                    ;;
                *)
                    echo "${bold}Video:   ${norm}${XDGVIDEO::-8}"
                    ;;
            esac
            ;;
        -i*|--i*)
            XDGIMAGE="$(xdg-mime query default image/png)" || XDGIMAGE="Not set!        "
            case $XDGIMAGE in
                *gwenview*|*Gwenview*)
                    echo "${bold}Image:   ${norm}Gwenview"
                    ;;
                *gimp*|*Gimp*|*GIMP*)
                    echo "${bold}Image:   ${norm}GIMP"
                    ;;
                *krita*|*Krita*)
                    echo "${bold}Image:   ${norm}Krita"
                    ;;
                *mtpaint*)
                    echo "${bold}Image:   ${norm}mtpaint"
                    ;;
                *)
                    echo "${bold}Image:   ${norm}${XDGIMAGE::-8}"
                    ;;
            esac
            ;;
        -t*|--t*)
            XDGTEXT="$(xdg-mime query default text/plain)"  || XDGTEXT="Not set!        "
            case $XDGTEXT in
                *code*)
                    echo "${bold}Text:    ${norm}VSCode"
                    ;;
                *atom*|*Atom*)
                    echo "${bold}Text:    ${norm}Atom"
                    ;;
                *gedit*|*Gedit*)
                    echo "${bold}Text:    ${norm}gedit"
                    ;;
                *mousepad*|*Mousepad*)
                    echo "${bold}Text:    ${norm}Mousepad"
                    ;;
                *notepadqq*|*Notepadqq*)
                    echo "${bold}Text:    ${norm}notepadqq"
                    ;;
                *geany*|*Geany*)
                    echo "${bold}Text:    ${norm}Geany"
                    ;;
                *)
                    echo "${bold}Text:    ${norm}${XDGTEXT::-8}"
                    ;;
            esac
            ;;
        *)
            echo "${bold}Default xdg applications:${norm}"
            XDGBROWSER="$(xdg-settings get default-web-browser)" || XDGBROWSER="Not set!        "
            echo
            case $XDGBROWSER in
                *Pale*|*pale*)
                    echo "${bold}Browser: ${norm}Pale Moon"
                    ;;
                *firefox*)
                    echo "${bold}Browser: ${norm}Firefox"
                    ;;
                *google*)
                    echo "${bold}Browser: ${norm}Google Chrome"
                    ;;
                *chromium*)
                    echo "${bold}Browser: ${norm}Chromium"
                    ;;
                *)
                    echo "${bold}Browser: ${norm}${XDGBROWSER::-8}"
                    ;;
            esac
            XDGMAILTO="$(xdg-mime query default x-scheme-handler/mailto)" || XDGMAILTO="Not set!        "
            case $XDGMAILTO in
                *thunderbird*|*Thunderbird*)
                    echo "${bold}Email:   ${norm}Thunderbird"
                    ;;
                *kmail*)
                    echo "${bold}Email:   ${norm}KMail"
                    ;;
                *)
                    echo "${bold}Email:   ${norm}${XDGMAILTO::-8}"
                    ;;
            esac
            XDGAUDIO="$(xdg-mime query default audio/flac)" || XDGAUDIO="Not set!        "
            case $XDGAUDIO in
                *audacious*|*Audacious*)
                    echo "${bold}Audio:   ${norm}Audacious"
                    ;;
                *mpv*)
                    echo "${bold}Audio:   ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    echo "${bold}Audio:   ${norm}VLC"
                    ;;
                *amarok*|*Amarok*)
                    echo "${bold}Audio:   ${norm}Amarok"
                    ;;
                *deadbeef*)
                    echo "${bold}Audio:   ${norm}DeaDBeeF"
                    ;;
                *)
                    echo "${bold}Audio:   ${norm}${XDGAUDIO::-8}"
                    ;;
            esac
            XDGVIDEO="$(xdg-mime query default video/mp4)" || XDGVIDEO="Not set!        "
            case $XDGVIDEO in
                *mpv*)
                    echo "${bold}Video:   ${norm}mpv"
                    ;;
                *vlc*|*VLC*)
                    echo "${bold}Video:   ${norm}VLC"
                    ;;
                *mplayer*)
                    echo "${bold}Video:   ${norm}Mplayer"
                    ;;
                *)
                    echo "${bold}Video:   ${norm}${XDGVIDEO::-8}"
                    ;;
            esac
            XDGIMAGE="$(xdg-mime query default image/png)" || XDGIMAGE="Not set!        "
            case $XDGIMAGE in
                *gwenview*|*Gwenview*)
                    echo "${bold}Image:   ${norm}Gwenview"
                    ;;
                *gimp*|*Gimp*|*GIMP*)
                    echo "${bold}Image:   ${norm}GIMP"
                    ;;
                *krita*|*Krita*)
                    echo "${bold}Image:   ${norm}Krita"
                    ;;
                *mtpaint*)
                    echo "${bold}Image:   ${norm}mtpaint"
                    ;;
                *)
                    echo "${bold}Image:   ${norm}${XDGIMAGE::-8}"
                    ;;
            esac
            XDGTEXT="$(xdg-mime query default text/plain)" || XDGTEXT="Not set!        "
            case $XDGTEXT in
                *code*)
                    echo "${bold}Text:    ${norm}VSCode"
                    ;;
                *atom*|*Atom*)
                    echo "${bold}Text:    ${norm}Atom"
                    ;;
                *gedit*|*Gedit*)
                    echo "${bold}Text:    ${norm}gedit"
                    ;;
                *mousepad*|*Mousepad*)
                    echo "${bold}Text:    ${norm}Mousepad"
                    ;;
                *notepadqq*|*Notepadqq*)
                    echo "${bold}Text:    ${norm}notepadqq"
                    ;;
                *geany*|*Geany*)
                    echo "${bold}Text:    ${norm}Geany"
                    ;;
                *)
                    echo "${bold}Text:    ${norm}${XDGTEXT::-8}"
                    ;;
            esac
            echo
    esac
}

programisinstalled "xdg-mime"
if [ "$return" = "1" ]; then
    programisinstalled "xdg-settings"
    if [ "$return" = "1" ]; then
    if [ ! -z "$2" ]; then
            case $3 in
                1)
                    bold=$(tput bold; tput setaf 1)
                    xdgfetchmain "$1"
                    ;;
                2)
                    bold=$(tput bold; tput setaf 2)
                    xdgfetchmain "$1"
                    ;;
                3)
                    bold=$(tput bold; tput setaf 3)
                    xdgfetchmain "$1"
                    ;;
                4)
                    bold=$(tput bold; tput setaf 4)
                    xdgfetchmain "$1"
                    ;;
                5)
                    bold=$(tput bold; tput setaf 5)
                    xdgfetchmain "$1"
                    ;;
                6)
                    bold=$(tput bold; tput setaf 6)
                    xdgfetchmain "$1"
                    ;;
                *)
                    bold=$(tput bold; tput setaf 7)
                    xdgfetchmain "$@"
                    ;;
            esac
        else
            xdgfetchmain "$@"
        fi
    else
        echo "xdg-settings is not installed!"
        exit 0
    fi
else
    echo "xdg-mime is not installed!"
    exit 0
fi