#!/bin/bash
# Installs and uninstalls apttool using wget

main () {
    case $1 in
        install)
            read -p "Install apttool to /usr/bin/apttool? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "apttool was not installed."
                exit 0
            fi
            wget -O /tmp/apttool https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/apttool/apttool.sh
            if [ -f "/tmp/apttool" ]; then
                wget -O /tmp/apttool.png https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/apttool/apttool.png
                if [ -f "/tmp/apttool.png" ]; then
                    wget -O /tmp/apttool.desktop https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/apttool/apttool.desktop
                        if [ -f "/tmp/apttool.desktop" ]; then
                            echo "Moving apttool to /usr/bin/apttool"
                            mv /tmp/apttool /usr/bin/apttool
                            echo "Making apttool executable"
                            chmod +x /usr/bin/apttool
                            echo "Moving apttool icon to /usr/share/icons/apttool.png"
                            mv /tmp/apttool.png /usr/share/icons/apttool.png
                            echo "Moving .desktop file to /usr/share/applications/apttool.desktop"
                            mv /tmp/apttool.desktop /usr/share/applications/apttool.desktop
                        else
                            echo ".desktop file download failed; try installing again."
                            rm -f /tmp/apttool.sh
                            rm -f /tmp/apttool.png
                            exit 0
                        fi
                else
                    echo "Icon download failed; try installing again."
                    rm -f /tmp/apttool.sh
                    exit 0
                fi
            else
                echo "apttool download failed; try installing again."
                exit 0
            fi
            ;;
        uninstall)
            read -p "Uninstall apttool from /usr/bin/apttool? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "apttool was not uninstalled."
                exit 0
            fi
            if [ -f "/usr/bin/apttool" ]; then
                rm -f /usr/bin/apttool
                echo "apttool has been removed!"
            else
                echo "/usr/bin/apttool does not exist!"
            fi
            if [ -f "/usr/share/icons/apttool.png" ]; then
                rm -f /usr/share/icons/apttool.png
                echo "Icon has been removed!"
            else
                echo "Icon for apttool does not exist!"
            fi
            if [ -f "/usr/share/applications/apttool.desktop" ]; then
                rm -f /usr/share/applications/apttool.desktop
                echo ".desktop file has been removed!"
            fi
            exit 0
            ;;
        *)
            echo "Usage:"
            echo "'sudo ./make install' for installation process"
            echo "'sudo ./make uninstall' for uninstallation process"
            exit 0
    esac
        
}

programisinstalled () {
  # set to 1 initially
  return=1
  # set to 0 if not found
  type "$1" >/dev/null 2>&1 || { return=0; }
  # return value
}

if [ "$EUID" -ne 0 ]; then
    echo "make install and uninstall must be ran as root!"
    main "help"
    exit 0
fi
programisinstalled "wget"
if [ "$return" = "1" ]; then
    main "$1"
else
    echo "wget is not installed; cannot download apttool."
fi