#!/bin/bash
# Installs and uninstalls mpv-zui using wget

main () {
    case $1 in
        install)
            read -p "Install mpv-zui to /usr/bin/mpv-zui? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "mpv-zui was not installed."
                exit 0
            fi
            wget -O /tmp/mpv-zui https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/mpv-zui/mpv-zui.sh || { echo "Download failed!" ; exit 0 ; }
            if [ -f "/tmp/mpv-zui" ]; then
                wget -O /tmp/mpv-zui.png https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/mpv-zui/mpv-zui.png || { echo "Download failed!" ; exit 0 ; }
                if [ -f "/tmp/mpv-zui.png" ]; then
                    wget -O /tmp/mpv-zui.desktop https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/mpv-zui/mpv-zui.desktop || { echo "Download failed!" ; exit 0 ; }
                        if [ -f "/tmp/mpv-zui.desktop" ]; then
                            echo "Moving mpv-zui to /usr/bin/mpv-zui"
                            mv /tmp/mpv-zui /usr/bin/mpv-zui
                            echo "Making mpv-zui executable"
                            chmod +x /usr/bin/mpv-zui
                            echo "Moving mpv-zui icon to /usr/share/icons/mpv-zui.png"
                            mv /tmp/mpv-zui.png /usr/share/icons/mpv-zui.png
                            echo "Moving .desktop file to /usr/share/applications/mpv-zui.desktop"
                            mv /tmp/mpv-zui.desktop /usr/share/applications/mpv-zui.desktop
                        else
                            echo ".desktop file download failed; try installing again."
                            rm -f /tmp/mpv-zui.sh
                            rm -f /tmp/mpv-zui.png
                            exit 0
                        fi
                else
                    echo "Icon download failed; try installing again."
                    rm -f /tmp/mpv-zui.sh
                    exit 0
                fi
            else
                echo "mpv-zui download failed; try installing again."
                exit 0
            fi
            ;;
        uninstall)
            read -p "Uninstall mpv-zui from /usr/bin/mpv-zui? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "mpv-zui was not uninstalled."
                exit 0
            fi
            if [ -f "/usr/bin/mpv-zui" ]; then
                rm -f /usr/bin/mpv-zui
                echo "mpv-zui has been removed!"
            else
                echo "/usr/bin/mpv-zui does not exist!"
            fi
            if [ -f "/usr/share/icons/mpv-zui.png" ]; then
                rm -f /usr/share/icons/mpv-zui.png
                echo "mpv-zui.png has been removed!"
            else
                echo "mpv-zui.png does not exist!"
            fi
            if [ -f "/usr/share/applications/mpv-zui.desktop" ]; then
                rm -f /usr/share/applications/mpv-zui.desktop
                echo "mpv-zui.desktop has been removed!"
            else
                echo "mpv-zui.desktop does not exist!"
            fi
            exit 0
            ;;
        help)
            echo "Usage:"
            echo "'sudo ./mpvzuiinst install' for installation process"
            echo "'sudo ./mpvzuiinst uninstall' for uninstallation process"
            exit 0
            ;;
        *)
            read -p "What would you like to do? install/uninstall "
            echo
            main "$REPLY"
    esac
        
}

programisinstalled () {
  # set to 1 initially
  return=1
  # set to 0 if not found
  type "$1" >/dev/null 2>&1 || { return=0; }
  # return value
}

if [ "$EUID" -ne 0 ]; then
    echo "apttinst install and uninstall must be ran as root!"
    main "help"
    exit 0
fi
programisinstalled "wget"
if [ "$return" = "1" ]; then
    main "$1"
else
    echo "wget is not installed; cannot download mpv-zui."
fi