#!/bin/bash
# Installs and uninstalls gpgpassman using wget

main () {
    case $1 in
        install)
            read -p "Install gpgpassman to /usr/bin/gpgpassman? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "gpgpassman was not installed."
                exit 0
            fi
            wget -O /tmp/gpgpassman https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/gpgpassman/gpgpassman.sh
            if [ -f "/tmp/gpgpassman" ]; then
                wget -O /tmp/gpgpassman.png https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/gpgpassman/gpgpassman.png
                if [ -f "/tmp/gpgpassman.png" ]; then
                    wget -O /tmp/gpgpassman.desktop https://raw.githubusercontent.com/simoniz0r/UsefulScripts/master/gpgpassman/gpgpassman.desktop
                        if [ -f "/tmp/gpgpassman.desktop" ]; then
                            echo "Moving gpgpassman to /usr/bin/gpgpassman"
                            mv /tmp/gpgpassman /usr/bin/gpgpassman
                            echo "Making gpgpassman executable"
                            chmod +x /usr/bin/gpgpassman
                            echo "Moving gpgpassman icon to /usr/share/icons/gpgpassman.png"
                            mv /tmp/gpgpassman.png /usr/share/icons/gpgpassman.png
                            echo "Moving .desktop file to /usr/share/applications/gpgpassman.desktop"
                            mv /tmp/gpgpassman.desktop /usr/share/applications/gpgpassman.desktop
                        else
                            echo ".desktop file download failed; try installing again."
                            rm -f /tmp/gpgpassman.sh
                            rm -f /tmp/gpgpassman.png
                            exit 0
                        fi
                else
                    echo "Icon download failed; try installing again."
                    rm -f /tmp/gpgpassman.sh
                    exit 0
                fi
            else
                echo "gpgpassman download failed; try installing again."
                exit 0
            fi
            ;;
        uninstall)
            read -p "Uninstall gpgpassman from /usr/bin/gpgpassman? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "gpgpassman was not uninstalled."
                exit 0
            fi
            if [ -f "/usr/bin/gpgpassman" ]; then
                rm -f /usr/bin/gpgpassman
                echo "gpgpassman has been removed!"
            else
                echo "/usr/bin/gpgpassman does not exist!"
            fi
            if [ -f "/usr/share/icons/gpgpassman.png" ]; then
                rm -f /usr/share/icons/gpgpassman.png
                echo "Icon has been removed!"
            else
                echo "Icon for gpgpassman does not exist!"
            fi
            if [ -f "/usr/share/applications/gpgpassman.desktop" ]; then
                rm -f /usr/share/applications/gpgpassman.desktop
                echo ".desktop file has been removed!"
            fi
            exit 0
            ;;
        *)
            echo "Usage:"
            echo "'sudo ./gpminst install' for installation process"
            echo "'sudo ./gpminst uninstall' for uninstallation process"
            exit 0
    esac
        
}

programisinstalled () {
  # set to 1 initially
  return=1
  # set to 0 if not found
  type "$1" >/dev/null 2>&1 || { return=0; }
  # return value
}

if [ "$EUID" -ne 0 ]; then
    echo "gpminst install and uninstall must be ran as root!"
    main "help"
    exit 0
fi
programisinstalled "wget"
if [ "$return" = "1" ]; then
    main "$1"
else
    echo "wget is not installed; cannot download gpgpassman."
fi
